sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: abc123
  wechat:
    appid: wx42773e61f3a0dcfa
    secret: 7406a792df34f41916a9299e73dde278
server:
  port: 8080

spring:
  redis:
    host: 192.168.239.135
    port: 6379
    password: 123321